### PR TITLE
Added proc-nexttick

### PR DESCRIPTION
**Pull request by tinchoz49**
This PR add support to use queueMicrotask when we use streamx in the browser.

### CODE REVIEW

**Comment by phated** [comment]
Why is this actually needed?

**Comment by tinchoz49** [comment]
Most bundler these days use a polyfill of process.nextTick based on setTimeout but modern browsers has queueMicrotask, a good replacement for process.nextTick in the browser. This PR provides that support.

**Comment by phated** [comment]
My understanding is that this library is meant for nodejs (but that doesn't stop you from using it in the browser). I think you'd just want to swap out that polyfill in your bundler, instead of adding a dependency here.

**Comment by tinchoz49** [comment]
It seems to be for the nodejs since it's using the `events` module too, so that's a good point, thank you

**Pull request closed without merging**
